# Generated by Django 4.2.7 on 2023-11-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('std', models.IntegerField(max_length=2)),
                ('section', models.CharField(max_length=1)),
                ('school', models.CharField(max_length=200)),
                ('ph_no', models.IntegerField(max_length=10, unique=True)),
            ],
        ),
    ]
