# Generated by Django 4.2.7 on 2023-11-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_data',
            name='ph_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='students_data',
            name='std',
            field=models.CharField(max_length=2),
        ),
    ]
